@startuml
|Турист|
start
:Просмотр найденных туров после поиска;
if (Тур найден?) then (да)
    :Забронировать;
    |Система|
    :Создать бронь на туриста;
    if (Бронь создалась?) then (да)
        |Турист|
        :Отображение подробностей брони;
        if (Оплатить бронь?) then (да)
            :Оплата брони;
            |Система|
            :Выполнение оплаты;
            :Генерация билета для пользователя;
            |Турист|
            :Получение билета;
            if (Нужно отменить билет?) then (да)
                |Система|
                :Отмена билета;
                stop
            else (нет)
                |Турист|
                :Отправиться в тур;
                stop
            endif
        else (нет)
            if (Время брони истекло?) then (да)
                |Система|
                :Автоматическая отмена брони;
                stop
            else (нет)
                |Турист|
                :Отмена вручную;
                stop
            endif
        endif        
    else (нет)
        |Система|
        :Сообщение об ошибке бронирования;
        stop
    endif
else (нет)
    :Выход из процесса;
    stop
endif
@enduml
