@startuml
|Туроператор|
start
:Туроператор вошёл в систему;
if (Туроператор будет создавать новый тур?) then (да)
    :Туроператор создаёт новый тур;
    :Созданый тур отправляется на модерацию;
else (нет)
    if (Туроператор будет редактировать уже имеющийся тур?) then (да)
        :Туроператор редактиует тур;
        :Туроператор отправляет изменения на модерацию;
    else (нет)
        :Туроператор выходит из системы;
        stop
    endif
endif
fork
    :Туроператор выходит из системы;
    stop
fork again
    :Тур отправился на модерацию;
    |Администратор|
    :Администратор модерирует тур;
    if (Тур прошёл модерацию?) then (да)
        :Тур публикуется в общий доступ;
    else (нет)
        :Оповещение с замечаниями отправляется туроператору;
    endif
    :Администратор закончил модерацию тура;

stop
@enduml